// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKs_hHcUABVMVa8-YSLbEQmQj2ZMkmgJ0',
    appId: '1:500417051991:web:94ff17b7865ddb6ecb9212',
    messagingSenderId: '500417051991',
    projectId: 'portfolio-e4742',
    authDomain: 'portfolio-e4742.firebaseapp.com',
    storageBucket: 'portfolio-e4742.appspot.com',
    measurementId: 'G-R9G1TYLE8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOrzDWel1xi3ynkxlJWgJFEW930VXcqbI',
    appId: '1:500417051991:android:11add218d58fa48acb9212',
    messagingSenderId: '500417051991',
    projectId: 'portfolio-e4742',
    storageBucket: 'portfolio-e4742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt1oK8C8poQze3J3Pneivl-ifI0iJ8wrc',
    appId: '1:500417051991:ios:1395e81a00a41082cb9212',
    messagingSenderId: '500417051991',
    projectId: 'portfolio-e4742',
    storageBucket: 'portfolio-e4742.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt1oK8C8poQze3J3Pneivl-ifI0iJ8wrc',
    appId: '1:500417051991:ios:1395e81a00a41082cb9212',
    messagingSenderId: '500417051991',
    projectId: 'portfolio-e4742',
    storageBucket: 'portfolio-e4742.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKs_hHcUABVMVa8-YSLbEQmQj2ZMkmgJ0',
    appId: '1:500417051991:web:c4b7899ecd7b1649cb9212',
    messagingSenderId: '500417051991',
    projectId: 'portfolio-e4742',
    authDomain: 'portfolio-e4742.firebaseapp.com',
    storageBucket: 'portfolio-e4742.appspot.com',
    measurementId: 'G-TREFB9TKLJ',
  );
}
